version = 0.1

[default.deploy.parameters]
stack_name = "lambda-large-file-cleansing"
resolve_s3 = true
s3_prefix = "lambda-large-file-cleansing"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
profile = "AdministratorAccess-450347635113"
